/*---------------------------------------------------------------------------*\
License 

   IBMFoam is distributed under the GNU Lesser General Public License (LGPL).
   
   You are free to copy and share this license text in its original form. 
   Modifying the wording of the license itself is not permitted.
   
   This license incorporates the rights and obligations of the 
   GNU General Public License (GPL) v3, 
   along with the additional permissions granted under the LGPL terms.
   
   A copy of the GNU Lesser General Public License should have been provided 
   with IBMFoam. If you did not receive one, it can be found online at:
      <http://www.gnu.org/licenses/lgpl.html>

InNamspace
    contactModel

Description
    Static class for storing material properties
\*---------------------------------------------------------------------------*/

#ifndef materialProperties_H
#define materialProperties_H

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{


class materialProperties
{
    public:

    static const HashTable<material_info,string,Hash<string>>& getMatProps()
    {
        return materialProps_;
    }

    static void matProps_insert
    (
        const string& material,
        const material_info matInfo
    )
    {
        materialProps_.insert(material,matInfo);
    }

    static HashTable<material_info,string,Hash<string>> materialProps_;

};

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
